package exception;

public class Demo {
    public static void main(String[] args) {
        System.out.println("demo inside exception package");
    }
}
